export enum AtomFamilies {
  pickUpFiltersVisibility = 'PICKUP_FILTERS_VISIBILITY',
  pickUpSearchQuery = 'PICKUP_SEARCH_QUERY',
  timePickerPopupVisibility = 'TIME_PICKER_POPUP_VISIBILITY',
  timePickerNumeralTimes = 'TIME_PICKER_NUMERAL_TIMES',
  activeLayer = 'ACTIVE_LAYER',
  timePickerMinimumDate = 'TIME_PICKER_MINIMUM_DATE',
  currentWindowBreakpoint = 'CURRENT_WINDOW_BREAK_POINT',
  napIndex = 'NAP_INDEX',
  napGroupIndex = 'NAP_GROUP_INDEX',
  napViewerVisibility = 'NAP_VIEWER_VISIBILITY',
  answerQuestionModal = 'ANSWER_QUESTION_MODAL',
  showMoreOptions = 'SHOW_MORE_OPTIONS',
  activeOption = 'ACTIVE_OPTIONS',
  activeItemID = 'ACTIVE_ITEM_ID',
  postsPickUp = 'POSTS_PICKUP',
  mentionPickUp = 'MENTION_PICKUP',
  giphyPickUp = 'GIPHY_PICKUP',
  mentionPopupVisibility = 'MENTION_POPUP_VISIBILITY',
  editLinkPopupVisibility = 'EDIT_LINK_POPUP_VISIBILITY',
  editLinkPopupLinkTextAndRef = 'EDIT_LINK_POPUP_LINK_TEXT_AND_REF',
}
