import { DatesHelperLib } from '@/helpers/dates'

type x = {
  countryCode: string
  countryName: string
  timeZone: DatesHelperLib.T.TimeZone
  GMTOffset: string
}

export const x: x[] = [
  {
    countryCode: 'AF',
    countryName: 'Afghanistan',
    timeZone: 'Asia/Kabul',
    GMTOffset: 'UTC +04:36',
  },
  {
    countryCode: 'AL',
    countryName: 'Albania',
    timeZone: 'Europe/Tirane',
    GMTOffset: 'UTC +01:19',
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    timeZone: 'Africa/Algiers',
    GMTOffset: 'UTC +00:12',
  },
  {
    countryCode: 'AS',
    countryName: 'American Samoa',
    timeZone: 'Pacific/Pago_Pago',
    GMTOffset: 'UTC +12:37',
  },
  {
    countryCode: 'AD',
    countryName: 'Andorra',
    timeZone: 'Europe/Andorra',
    GMTOffset: 'UTC +00:06',
  },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    timeZone: 'Africa/Luanda',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'AI',
    countryName: 'Anguilla',
    timeZone: 'America/Anguilla',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Casey',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Davis',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/DumontDUrville',
    GMTOffset: 'UTC +09:48',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Mawson',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/McMurdo',
    GMTOffset: 'UTC +11:39',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Palmer',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Rothera',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Syowa',
    GMTOffset: 'UTC +03:06',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Troll',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AQ',
    countryName: 'Antarctica',
    timeZone: 'Antarctica/Vostok',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    timeZone: 'America/Antigua',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Buenos_Aires',
    GMTOffset: 'UTC -03:53',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Catamarca',
    GMTOffset: 'UTC -04:23',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Cordoba',
    GMTOffset: 'UTC -04:16',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Jujuy',
    GMTOffset: 'UTC -04:21',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/La_Rioja',
    GMTOffset: 'UTC -04:27',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Mendoza',
    GMTOffset: 'UTC -04:35',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Rio_Gallegos',
    GMTOffset: 'UTC -04:36',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Salta',
    GMTOffset: 'UTC -04:21',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/San_Juan',
    GMTOffset: 'UTC -04:34',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/San_Luis',
    GMTOffset: 'UTC -04:25',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Tucuman',
    GMTOffset: 'UTC -04:20',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    timeZone: 'America/Argentina/Ushuaia',
    GMTOffset: 'UTC -04:33',
  },
  {
    countryCode: 'AM',
    countryName: 'Armenia',
    timeZone: 'Asia/Yerevan',
    GMTOffset: 'UTC +02:58',
  },
  {
    countryCode: 'AW',
    countryName: 'Aruba',
    timeZone: 'America/Aruba',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Antarctica/Macquarie',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Adelaide',
    GMTOffset: 'UTC +09:14',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Brisbane',
    GMTOffset: 'UTC +10:12',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Broken_Hill',
    GMTOffset: 'UTC +09:25',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Darwin',
    GMTOffset: 'UTC +08:43',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Eucla',
    GMTOffset: 'UTC +08:35',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Hobart',
    GMTOffset: 'UTC +09:49',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Lindeman',
    GMTOffset: 'UTC +09:55',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Lord_Howe',
    GMTOffset: 'UTC +10:36',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Melbourne',
    GMTOffset: 'UTC +09:39',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Perth',
    GMTOffset: 'UTC +07:43',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    timeZone: 'Australia/Sydney',
    GMTOffset: 'UTC +10:04',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    timeZone: 'Europe/Vienna',
    GMTOffset: 'UTC +01:05',
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    timeZone: 'Asia/Baku',
    GMTOffset: 'UTC +03:19',
  },
  {
    countryCode: 'BS',
    countryName: 'Bahamas',
    timeZone: 'America/Nassau',
    GMTOffset: 'UTC -05:17',
  },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    timeZone: 'Asia/Bahrain',
    GMTOffset: 'UTC +03:26',
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    timeZone: 'Asia/Dhaka',
    GMTOffset: 'UTC +06:01',
  },
  {
    countryCode: 'BB',
    countryName: 'Barbados',
    timeZone: 'America/Barbados',
    GMTOffset: 'UTC -03:58',
  },
  {
    countryCode: 'BY',
    countryName: 'Belarus',
    timeZone: 'Europe/Minsk',
    GMTOffset: 'UTC +01:50',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    timeZone: 'Europe/Brussels',
    GMTOffset: 'UTC +00:17',
  },
  {
    countryCode: 'BZ',
    countryName: 'Belize',
    timeZone: 'America/Belize',
    GMTOffset: 'UTC -05:52',
  },
  {
    countryCode: 'BJ',
    countryName: 'Benin',
    timeZone: 'Africa/Porto-Novo',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'BM',
    countryName: 'Bermuda',
    timeZone: 'Atlantic/Bermuda',
    GMTOffset: 'UTC -04:19',
  },
  {
    countryCode: 'BT',
    countryName: 'Bhutan',
    timeZone: 'Asia/Thimphu',
    GMTOffset: 'UTC +05:58',
  },
  {
    countryCode: 'BO',
    countryName: 'Bolivia, Plurinational State of',
    timeZone: 'America/La_Paz',
    GMTOffset: 'UTC -04:32',
  },
  {
    countryCode: 'BQ',
    countryName: 'Bonaire, Sint Eustatius and Saba',
    timeZone: 'America/Kralendijk',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    timeZone: 'Europe/Sarajevo',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'BW',
    countryName: 'Botswana',
    timeZone: 'Africa/Gaborone',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Araguaina',
    GMTOffset: 'UTC -03:12',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Bahia',
    GMTOffset: 'UTC -02:34',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Belem',
    GMTOffset: 'UTC -03:13',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Boa_Vista',
    GMTOffset: 'UTC -04:02',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Campo_Grande',
    GMTOffset: 'UTC -03:38',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Cuiaba',
    GMTOffset: 'UTC -03:44',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Eirunepe',
    GMTOffset: 'UTC -04:39',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Fortaleza',
    GMTOffset: 'UTC -02:34',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Maceio',
    GMTOffset: 'UTC -02:22',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Manaus',
    GMTOffset: 'UTC -04:00',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Noronha',
    GMTOffset: 'UTC -02:09',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Porto_Velho',
    GMTOffset: 'UTC -04:15',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Recife',
    GMTOffset: 'UTC -02:19',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Rio_Branco',
    GMTOffset: 'UTC -04:31',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Santarem',
    GMTOffset: 'UTC -03:38',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    timeZone: 'America/Sao_Paulo',
    GMTOffset: 'UTC -03:06',
  },
  {
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    timeZone: 'Indian/Chagos',
    GMTOffset: 'UTC +04:49',
  },
  {
    countryCode: 'BN',
    countryName: 'Brunei Darussalam',
    timeZone: 'Asia/Brunei',
    GMTOffset: 'UTC +07:39',
  },
  {
    countryCode: 'BG',
    countryName: 'Bulgaria',
    timeZone: 'Europe/Sofia',
    GMTOffset: 'UTC +01:33',
  },
  {
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    timeZone: 'Africa/Ouagadougou',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'BI',
    countryName: 'Burundi',
    timeZone: 'Africa/Bujumbura',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'KH',
    countryName: 'Cambodia',
    timeZone: 'Asia/Phnom_Penh',
    GMTOffset: 'UTC +06:42',
  },
  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    timeZone: 'Africa/Douala',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Atikokan',
    GMTOffset: 'UTC -05:18',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Blanc-Sablon',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Cambridge_Bay',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Creston',
    GMTOffset: 'UTC -07:28',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Dawson',
    GMTOffset: 'UTC -09:17',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Dawson_Creek',
    GMTOffset: 'UTC -08:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Edmonton',
    GMTOffset: 'UTC -07:33',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Fort_Nelson',
    GMTOffset: 'UTC -08:10',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Glace_Bay',
    GMTOffset: 'UTC -03:59',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Goose_Bay',
    GMTOffset: 'UTC -04:01',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Halifax',
    GMTOffset: 'UTC -04:14',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Inuvik',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Iqaluit',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Moncton',
    GMTOffset: 'UTC -04:19',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Nipigon',
    GMTOffset: 'UTC -05:53',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Pangnirtung',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Rainy_River',
    GMTOffset: 'UTC -06:18',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Rankin_Inlet',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Regina',
    GMTOffset: 'UTC -06:58',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Resolute',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/St_Johns',
    GMTOffset: 'UTC -03:30',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Swift_Current',
    GMTOffset: 'UTC -07:11',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Thunder_Bay',
    GMTOffset: 'UTC -05:57',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Toronto',
    GMTOffset: 'UTC -05:17',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Vancouver',
    GMTOffset: 'UTC -08:12',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Whitehorse',
    GMTOffset: 'UTC -09:00',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Winnipeg',
    GMTOffset: 'UTC -06:28',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    timeZone: 'America/Yellowknife',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'CV',
    countryName: 'Cape Verde',
    timeZone: 'Atlantic/Cape_Verde',
    GMTOffset: 'UTC -01:34',
  },
  {
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    timeZone: 'America/Cayman',
    GMTOffset: 'UTC -05:18',
  },
  {
    countryCode: 'CF',
    countryName: 'Central African Republic',
    timeZone: 'Africa/Bangui',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'TD',
    countryName: 'Chad',
    timeZone: 'Africa/Ndjamena',
    GMTOffset: 'UTC +01:00',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'America/Punta_Arenas',
    GMTOffset: 'UTC -04:43',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'America/Santiago',
    GMTOffset: 'UTC -04:42',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    timeZone: 'Pacific/Easter',
    GMTOffset: 'UTC -07:17',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    timeZone: 'Asia/Shanghai',
    GMTOffset: 'UTC +08:05',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    timeZone: 'Asia/Urumqi',
    GMTOffset: 'UTC +05:50',
  },
  {
    countryCode: 'CX',
    countryName: 'Christmas Island',
    timeZone: 'Indian/Christmas',
    GMTOffset: 'UTC +07:02',
  },
  {
    countryCode: 'CC',
    countryName: 'Cocos (Keeling) Islands',
    timeZone: 'Indian/Cocos',
    GMTOffset: 'UTC +06:27',
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    timeZone: 'America/Bogota',
    GMTOffset: 'UTC -04:56',
  },
  {
    countryCode: 'KM',
    countryName: 'Comoros',
    timeZone: 'Indian/Comoro',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'CG',
    countryName: 'Congo',
    timeZone: 'Africa/Brazzaville',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'CD',
    countryName: 'Congo, the Democratic Republic of the',
    timeZone: 'Africa/Kinshasa',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'CD',
    countryName: 'Congo, the Democratic Republic of the',
    timeZone: 'Africa/Lubumbashi',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'CK',
    countryName: 'Cook Islands',
    timeZone: 'Pacific/Rarotonga',
    GMTOffset: 'UTC +13:20',
  },
  {
    countryCode: 'CR',
    countryName: 'Costa Rica',
    timeZone: 'America/Costa_Rica',
    GMTOffset: 'UTC -05:36',
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    timeZone: 'Europe/Zagreb',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'CU',
    countryName: 'Cuba',
    timeZone: 'America/Havana',
    GMTOffset: 'UTC -05:29',
  },
  {
    countryCode: 'CW',
    countryName: 'Curaçao',
    timeZone: 'America/Curacao',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    timeZone: 'Asia/Famagusta',
    GMTOffset: 'UTC +02:15',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    timeZone: 'Asia/Nicosia',
    GMTOffset: 'UTC +02:13',
  },
  {
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    timeZone: 'Europe/Prague',
    GMTOffset: 'UTC +00:57',
  },
  {
    countryCode: 'CI',
    countryName: "Côte d'Ivoire",
    timeZone: 'Africa/Abidjan',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    timeZone: 'Europe/Copenhagen',
    GMTOffset: 'UTC +00:50',
  },
  {
    countryCode: 'DJ',
    countryName: 'Djibouti',
    timeZone: 'Africa/Djibouti',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'DM',
    countryName: 'Dominica',
    timeZone: 'America/Dominica',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    timeZone: 'America/Santo_Domingo',
    GMTOffset: 'UTC -04:39',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    timeZone: 'America/Guayaquil',
    GMTOffset: 'UTC -05:19',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    timeZone: 'Pacific/Galapagos',
    GMTOffset: 'UTC -05:58',
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    timeZone: 'Africa/Cairo',
    GMTOffset: 'UTC +02:05',
  },
  {
    countryCode: 'SV',
    countryName: 'El Salvador',
    timeZone: 'America/El_Salvador',
    GMTOffset: 'UTC -05:56',
  },
  {
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    timeZone: 'Africa/Malabo',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'ER',
    countryName: 'Eritrea',
    timeZone: 'Africa/Asmara',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'EE',
    countryName: 'Estonia',
    timeZone: 'Europe/Tallinn',
    GMTOffset: 'UTC +01:39',
  },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    timeZone: 'Africa/Addis_Ababa',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    timeZone: 'Atlantic/Stanley',
    GMTOffset: 'UTC -03:51',
  },
  {
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    timeZone: 'Atlantic/Faroe',
    GMTOffset: 'UTC -00:27',
  },
  {
    countryCode: 'FJ',
    countryName: 'Fiji',
    timeZone: 'Pacific/Fiji',
    GMTOffset: 'UTC +11:55',
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    timeZone: 'Europe/Helsinki',
    GMTOffset: 'UTC +01:39',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    timeZone: 'Europe/Paris',
    GMTOffset: 'UTC +00:09',
  },
  {
    countryCode: 'GF',
    countryName: 'French Guiana',
    timeZone: 'America/Cayenne',
    GMTOffset: 'UTC -03:29',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Gambier',
    GMTOffset: 'UTC -08:59',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Marquesas',
    GMTOffset: 'UTC -09:18',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    timeZone: 'Pacific/Tahiti',
    GMTOffset: 'UTC -09:58',
  },
  {
    countryCode: 'TF',
    countryName: 'French Southern Territories',
    timeZone: 'Indian/Kerguelen',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'GA',
    countryName: 'Gabon',
    timeZone: 'Africa/Libreville',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'GM',
    countryName: 'Gambia',
    timeZone: 'Africa/Banjul',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    timeZone: 'Asia/Tbilisi',
    GMTOffset: 'UTC +02:59',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    timeZone: 'Europe/Berlin',
    GMTOffset: 'UTC +00:53',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    timeZone: 'Europe/Busingen',
    GMTOffset: 'UTC +00:34',
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    timeZone: 'Africa/Accra',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'GI',
    countryName: 'Gibraltar',
    timeZone: 'Europe/Gibraltar',
    GMTOffset: 'UTC -00:21',
  },
  {
    countryCode: 'GR',
    countryName: 'Greece',
    timeZone: 'Europe/Athens',
    GMTOffset: 'UTC +01:34',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Danmarkshavn',
    GMTOffset: 'UTC -01:14',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Nuuk',
    GMTOffset: 'UTC -03:26',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Scoresbysund',
    GMTOffset: 'UTC -01:27',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    timeZone: 'America/Thule',
    GMTOffset: 'UTC -04:35',
  },
  {
    countryCode: 'GD',
    countryName: 'Grenada',
    timeZone: 'America/Grenada',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    timeZone: 'America/Guadeloupe',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'GU',
    countryName: 'Guam',
    timeZone: 'Pacific/Guam',
    GMTOffset: 'UTC -14:21',
  },
  {
    countryCode: 'GT',
    countryName: 'Guatemala',
    timeZone: 'America/Guatemala',
    GMTOffset: 'UTC -06:02',
  },
  {
    countryCode: 'GG',
    countryName: 'Guernsey',
    timeZone: 'Europe/Guernsey',
    GMTOffset: 'UTC -00:01',
  },
  {
    countryCode: 'GN',
    countryName: 'Guinea',
    timeZone: 'Africa/Conakry',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    timeZone: 'Africa/Bissau',
    GMTOffset: 'UTC -01:02',
  },
  {
    countryCode: 'GY',
    countryName: 'Guyana',
    timeZone: 'America/Guyana',
    GMTOffset: 'UTC -03:52',
  },
  {
    countryCode: 'HT',
    countryName: 'Haiti',
    timeZone: 'America/Port-au-Prince',
    GMTOffset: 'UTC -04:49',
  },
  {
    countryCode: 'VA',
    countryName: 'Holy See (Vatican City State)',
    timeZone: 'Europe/Vatican',
    GMTOffset: 'UTC +00:49',
  },
  {
    countryCode: 'HN',
    countryName: 'Honduras',
    timeZone: 'America/Tegucigalpa',
    GMTOffset: 'UTC -05:48',
  },
  {
    countryCode: 'HK',
    countryName: 'Hong Kong',
    timeZone: 'Asia/Hong_Kong',
    GMTOffset: 'UTC +07:36',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    timeZone: 'Europe/Budapest',
    GMTOffset: 'UTC +01:16',
  },
  {
    countryCode: 'IS',
    countryName: 'Iceland',
    timeZone: 'Atlantic/Reykjavik',
    GMTOffset: 'UTC -01:28',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    timeZone: 'Asia/Kolkata',
    GMTOffset: 'UTC +05:53',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Jakarta',
    GMTOffset: 'UTC +07:07',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Jayapura',
    GMTOffset: 'UTC +09:22',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Makassar',
    GMTOffset: 'UTC +07:57',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    timeZone: 'Asia/Pontianak',
    GMTOffset: 'UTC +07:17',
  },
  {
    countryCode: 'IR',
    countryName: 'Iran, Islamic Republic of',
    timeZone: 'Asia/Tehran',
    GMTOffset: 'UTC +03:25',
  },
  {
    countryCode: 'IQ',
    countryName: 'Iraq',
    timeZone: 'Asia/Baghdad',
    GMTOffset: 'UTC +02:57',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    timeZone: 'Europe/Dublin',
    GMTOffset: 'UTC -00:25',
  },
  {
    countryCode: 'IM',
    countryName: 'Isle of Man',
    timeZone: 'Europe/Isle_of_Man',
    GMTOffset: 'UTC -00:01',
  },
  {
    countryCode: 'IL',
    countryName: 'Israel',
    timeZone: 'Asia/Jerusalem',
    GMTOffset: 'UTC +02:20',
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    timeZone: 'Europe/Rome',
    GMTOffset: 'UTC +00:49',
  },
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    timeZone: 'America/Jamaica',
    GMTOffset: 'UTC -05:07',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    timeZone: 'Asia/Tokyo',
    GMTOffset: 'UTC +09:18',
  },
  {
    countryCode: 'JE',
    countryName: 'Jersey',
    timeZone: 'Europe/Jersey',
    GMTOffset: 'UTC -00:01',
  },
  {
    countryCode: 'JO',
    countryName: 'Jordan',
    timeZone: 'Asia/Amman',
    GMTOffset: 'UTC +02:23',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Almaty',
    GMTOffset: 'UTC +05:07',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Aqtau',
    GMTOffset: 'UTC +03:21',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Aqtobe',
    GMTOffset: 'UTC +03:48',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Atyrau',
    GMTOffset: 'UTC +03:27',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Oral',
    GMTOffset: 'UTC +03:25',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Qostanay',
    GMTOffset: 'UTC +04:14',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    timeZone: 'Asia/Qyzylorda',
    GMTOffset: 'UTC +04:21',
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    timeZone: 'Africa/Nairobi',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Kanton',
    GMTOffset: 'UTC',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Kiritimati',
    GMTOffset: 'UTC -10:29',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    timeZone: 'Pacific/Tarawa',
    GMTOffset: 'UTC +11:32',
  },
  {
    countryCode: 'KP',
    countryName: "Korea, Democratic People's Republic of",
    timeZone: 'Asia/Pyongyang',
    GMTOffset: 'UTC +08:23',
  },
  {
    countryCode: 'KR',
    countryName: 'Korea, Republic of',
    timeZone: 'Asia/Seoul',
    GMTOffset: 'UTC +08:27',
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    timeZone: 'Asia/Kuwait',
    GMTOffset: 'UTC +03:06',
  },
  {
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    timeZone: 'Asia/Bishkek',
    GMTOffset: 'UTC +04:58',
  },
  {
    countryCode: 'LA',
    countryName: "Lao People's Democratic Republic",
    timeZone: 'Asia/Vientiane',
    GMTOffset: 'UTC +06:42',
  },
  {
    countryCode: 'LV',
    countryName: 'Latvia',
    timeZone: 'Europe/Riga',
    GMTOffset: 'UTC +01:36',
  },
  {
    countryCode: 'LB',
    countryName: 'Lebanon',
    timeZone: 'Asia/Beirut',
    GMTOffset: 'UTC +02:22',
  },
  {
    countryCode: 'LS',
    countryName: 'Lesotho',
    timeZone: 'Africa/Maseru',
    GMTOffset: 'UTC +01:52',
  },
  {
    countryCode: 'LR',
    countryName: 'Liberia',
    timeZone: 'Africa/Monrovia',
    GMTOffset: 'UTC -00:43',
  },
  {
    countryCode: 'LY',
    countryName: 'Libya',
    timeZone: 'Africa/Tripoli',
    GMTOffset: 'UTC +00:52',
  },
  {
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    timeZone: 'Europe/Vaduz',
    GMTOffset: 'UTC +00:34',
  },
  {
    countryCode: 'LT',
    countryName: 'Lithuania',
    timeZone: 'Europe/Vilnius',
    GMTOffset: 'UTC +01:41',
  },
  {
    countryCode: 'LU',
    countryName: 'Luxembourg',
    timeZone: 'Europe/Luxembourg',
    GMTOffset: 'UTC +00:24',
  },
  {
    countryCode: 'MO',
    countryName: 'Macao',
    timeZone: 'Asia/Macau',
    GMTOffset: 'UTC +07:34',
  },
  {
    countryCode: 'MK',
    countryName: 'Macedonia, the Former Yugoslav Republic of',
    timeZone: 'Europe/Skopje',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'MG',
    countryName: 'Madagascar',
    timeZone: 'Indian/Antananarivo',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'MW',
    countryName: 'Malawi',
    timeZone: 'Africa/Blantyre',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    timeZone: 'Asia/Kuala_Lumpur',
    GMTOffset: 'UTC +06:46',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    timeZone: 'Asia/Kuching',
    GMTOffset: 'UTC +07:21',
  },
  {
    countryCode: 'MV',
    countryName: 'Maldives',
    timeZone: 'Indian/Maldives',
    GMTOffset: 'UTC +04:54',
  },
  {
    countryCode: 'ML',
    countryName: 'Mali',
    timeZone: 'Africa/Bamako',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    timeZone: 'Europe/Malta',
    GMTOffset: 'UTC +00:58',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    timeZone: 'Pacific/Kwajalein',
    GMTOffset: 'UTC +11:09',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    timeZone: 'Pacific/Majuro',
    GMTOffset: 'UTC +11:24',
  },
  {
    countryCode: 'MQ',
    countryName: 'Martinique',
    timeZone: 'America/Martinique',
    GMTOffset: 'UTC -04:04',
  },
  {
    countryCode: 'MR',
    countryName: 'Mauritania',
    timeZone: 'Africa/Nouakchott',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    timeZone: 'Indian/Mauritius',
    GMTOffset: 'UTC +03:50',
  },
  {
    countryCode: 'YT',
    countryName: 'Mayotte',
    timeZone: 'Indian/Mayotte',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Bahia_Banderas',
    GMTOffset: 'UTC -07:01',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Cancun',
    GMTOffset: 'UTC -05:47',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Chihuahua',
    GMTOffset: 'UTC -07:04',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Hermosillo',
    GMTOffset: 'UTC -07:23',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Matamoros',
    GMTOffset: 'UTC -06:40',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Mazatlan',
    GMTOffset: 'UTC -07:05',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Merida',
    GMTOffset: 'UTC -05:58',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Mexico_City',
    GMTOffset: 'UTC -06:36',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Monterrey',
    GMTOffset: 'UTC -06:41',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Ojinaga',
    GMTOffset: 'UTC -06:57',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    timeZone: 'America/Tijuana',
    GMTOffset: 'UTC -07:48',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Chuuk',
    GMTOffset: 'UTC -13:52',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Kosrae',
    GMTOffset: 'UTC -13:08',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia, Federated States of',
    timeZone: 'Pacific/Pohnpei',
    GMTOffset: 'UTC -13:27',
  },
  {
    countryCode: 'MD',
    countryName: 'Moldova, Republic of',
    timeZone: 'Europe/Chisinau',
    GMTOffset: 'UTC +01:55',
  },
  {
    countryCode: 'MC',
    countryName: 'Monaco',
    timeZone: 'Europe/Monaco',
    GMTOffset: 'UTC +00:29',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Choibalsan',
    GMTOffset: 'UTC +07:38',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Hovd',
    GMTOffset: 'UTC +06:06',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    timeZone: 'Asia/Ulaanbaatar',
    GMTOffset: 'UTC +07:07',
  },
  {
    countryCode: 'ME',
    countryName: 'Montenegro',
    timeZone: 'Europe/Podgorica',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'MS',
    countryName: 'Montserrat',
    timeZone: 'America/Montserrat',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    timeZone: 'Africa/Casablanca',
    GMTOffset: 'UTC -00:30',
  },
  {
    countryCode: 'MZ',
    countryName: 'Mozambique',
    timeZone: 'Africa/Maputo',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'MM',
    countryName: 'Myanmar',
    timeZone: 'Asia/Yangon',
    GMTOffset: 'UTC +06:24',
  },
  {
    countryCode: 'NA',
    countryName: 'Namibia',
    timeZone: 'Africa/Windhoek',
    GMTOffset: 'UTC +01:08',
  },
  {
    countryCode: 'NR',
    countryName: 'Nauru',
    timeZone: 'Pacific/Nauru',
    GMTOffset: 'UTC +11:07',
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    timeZone: 'Asia/Kathmandu',
    GMTOffset: 'UTC +05:41',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    timeZone: 'Europe/Amsterdam',
    GMTOffset: 'UTC +00:19',
  },
  {
    countryCode: 'NC',
    countryName: 'New Caledonia',
    timeZone: 'Pacific/Noumea',
    GMTOffset: 'UTC +11:05',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    timeZone: 'Pacific/Auckland',
    GMTOffset: 'UTC +11:39',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    timeZone: 'Pacific/Chatham',
    GMTOffset: 'UTC +12:13',
  },
  {
    countryCode: 'NI',
    countryName: 'Nicaragua',
    timeZone: 'America/Managua',
    GMTOffset: 'UTC -05:45',
  },
  {
    countryCode: 'NE',
    countryName: 'Niger',
    timeZone: 'Africa/Niamey',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    timeZone: 'Africa/Lagos',
    GMTOffset: 'UTC +00:13',
  },
  {
    countryCode: 'NU',
    countryName: 'Niue',
    timeZone: 'Pacific/Niue',
    GMTOffset: 'UTC -11:19',
  },
  {
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    timeZone: 'Pacific/Norfolk',
    GMTOffset: 'UTC +11:11',
  },
  {
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    timeZone: 'Pacific/Saipan',
    GMTOffset: 'UTC -14:21',
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    timeZone: 'Europe/Oslo',
    GMTOffset: 'UTC +00:43',
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    timeZone: 'Asia/Muscat',
    GMTOffset: 'UTC +03:41',
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    timeZone: 'Asia/Karachi',
    GMTOffset: 'UTC +04:28',
  },
  {
    countryCode: 'PW',
    countryName: 'Palau',
    timeZone: 'Pacific/Palau',
    GMTOffset: 'UTC -15:02',
  },
  {
    countryCode: 'PS',
    countryName: 'Palestine, State of',
    timeZone: 'Asia/Gaza',
    GMTOffset: 'UTC +02:17',
  },
  {
    countryCode: 'PS',
    countryName: 'Palestine, State of',
    timeZone: 'Asia/Hebron',
    GMTOffset: 'UTC +02:20',
  },
  {
    countryCode: 'PA',
    countryName: 'Panama',
    timeZone: 'America/Panama',
    GMTOffset: 'UTC -05:18',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    timeZone: 'Pacific/Bougainville',
    GMTOffset: 'UTC +10:22',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    timeZone: 'Pacific/Port_Moresby',
    GMTOffset: 'UTC +09:48',
  },
  {
    countryCode: 'PY',
    countryName: 'Paraguay',
    timeZone: 'America/Asuncion',
    GMTOffset: 'UTC -03:50',
  },
  {
    countryCode: 'PE',
    countryName: 'Peru',
    timeZone: 'America/Lima',
    GMTOffset: 'UTC -05:08',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    timeZone: 'Asia/Manila',
    GMTOffset: 'UTC -15:56',
  },
  {
    countryCode: 'PN',
    countryName: 'Pitcairn',
    timeZone: 'Pacific/Pitcairn',
    GMTOffset: 'UTC -08:40',
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    timeZone: 'Europe/Warsaw',
    GMTOffset: 'UTC +01:24',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    timeZone: 'Atlantic/Azores',
    GMTOffset: 'UTC -01:42',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    timeZone: 'Atlantic/Madeira',
    GMTOffset: 'UTC -01:07',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    timeZone: 'Europe/Lisbon',
    GMTOffset: 'UTC -00:36',
  },
  {
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    timeZone: 'America/Puerto_Rico',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'QA',
    countryName: 'Qatar',
    timeZone: 'Asia/Qatar',
    GMTOffset: 'UTC +03:26',
  },
  {
    countryCode: 'RO',
    countryName: 'Romania',
    timeZone: 'Europe/Bucharest',
    GMTOffset: 'UTC +01:44',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Anadyr',
    GMTOffset: 'UTC +11:49',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Barnaul',
    GMTOffset: 'UTC +05:35',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Chita',
    GMTOffset: 'UTC +07:33',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Irkutsk',
    GMTOffset: 'UTC +06:57',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Kamchatka',
    GMTOffset: 'UTC +10:34',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Khandyga',
    GMTOffset: 'UTC +09:02',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Krasnoyarsk',
    GMTOffset: 'UTC +06:11',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Magadan',
    GMTOffset: 'UTC +10:03',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Novokuznetsk',
    GMTOffset: 'UTC +05:48',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Novosibirsk',
    GMTOffset: 'UTC +05:31',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Omsk',
    GMTOffset: 'UTC +04:53',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Sakhalin',
    GMTOffset: 'UTC +09:30',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Srednekolymsk',
    GMTOffset: 'UTC +10:14',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Tomsk',
    GMTOffset: 'UTC +05:39',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Ust-Nera',
    GMTOffset: 'UTC +09:32',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Vladivostok',
    GMTOffset: 'UTC +08:47',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Yakutsk',
    GMTOffset: 'UTC +08:38',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Asia/Yekaterinburg',
    GMTOffset: 'UTC +04:02',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Astrakhan',
    GMTOffset: 'UTC +03:12',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Kaliningrad',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Kirov',
    GMTOffset: 'UTC +03:18',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Moscow',
    GMTOffset: 'UTC +02:30',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Samara',
    GMTOffset: 'UTC +03:20',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Saratov',
    GMTOffset: 'UTC +03:04',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Ulyanovsk',
    GMTOffset: 'UTC +03:13',
  },
  {
    countryCode: 'RU',
    countryName: 'Russian Federation',
    timeZone: 'Europe/Volgograd',
    GMTOffset: 'UTC +02:57',
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    timeZone: 'Africa/Kigali',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'RE',
    countryName: 'Réunion',
    timeZone: 'Indian/Reunion',
    GMTOffset: 'UTC +03:41',
  },
  {
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    timeZone: 'America/St_Barthelemy',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    timeZone: 'Atlantic/St_Helena',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    timeZone: 'America/St_Kitts',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    timeZone: 'America/St_Lucia',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'MF',
    countryName: 'Saint Martin (French part)',
    timeZone: 'America/Marigot',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    timeZone: 'America/Miquelon',
    GMTOffset: 'UTC -03:44',
  },
  {
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    timeZone: 'America/St_Vincent',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'WS',
    countryName: 'Samoa',
    timeZone: 'Pacific/Apia',
    GMTOffset: 'UTC +12:33',
  },
  {
    countryCode: 'SM',
    countryName: 'San Marino',
    timeZone: 'Europe/San_Marino',
    GMTOffset: 'UTC +00:49',
  },
  {
    countryCode: 'ST',
    countryName: 'Sao Tome and Principe',
    timeZone: 'Africa/Sao_Tome',
    GMTOffset: 'UTC +00:26',
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    timeZone: 'Asia/Riyadh',
    GMTOffset: 'UTC +03:06',
  },
  {
    countryCode: 'SN',
    countryName: 'Senegal',
    timeZone: 'Africa/Dakar',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'RS',
    countryName: 'Serbia',
    timeZone: 'Europe/Belgrade',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    timeZone: 'Indian/Mahe',
    GMTOffset: 'UTC +03:41',
  },
  {
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    timeZone: 'Africa/Freetown',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    timeZone: 'Asia/Singapore',
    GMTOffset: 'UTC +06:55',
  },
  {
    countryCode: 'SX',
    countryName: 'Sint Maarten (Dutch part)',
    timeZone: 'America/Lower_Princes',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    timeZone: 'Europe/Bratislava',
    GMTOffset: 'UTC +00:57',
  },
  {
    countryCode: 'SI',
    countryName: 'Slovenia',
    timeZone: 'Europe/Ljubljana',
    GMTOffset: 'UTC +01:22',
  },
  {
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    timeZone: 'Pacific/Guadalcanal',
    GMTOffset: 'UTC +10:39',
  },
  {
    countryCode: 'SO',
    countryName: 'Somalia',
    timeZone: 'Africa/Mogadishu',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    timeZone: 'Africa/Johannesburg',
    GMTOffset: 'UTC +01:52',
  },
  {
    countryCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    timeZone: 'Atlantic/South_Georgia',
    GMTOffset: 'UTC -02:26',
  },
  {
    countryCode: 'SS',
    countryName: 'South Sudan',
    timeZone: 'Africa/Juba',
    GMTOffset: 'UTC +02:06',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Africa/Ceuta',
    GMTOffset: 'UTC -00:21',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Atlantic/Canary',
    GMTOffset: 'UTC -01:01',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    timeZone: 'Europe/Madrid',
    GMTOffset: 'UTC -00:14',
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    timeZone: 'Asia/Colombo',
    GMTOffset: 'UTC +05:19',
  },
  {
    countryCode: 'SD',
    countryName: 'Sudan',
    timeZone: 'Africa/Khartoum',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'SR',
    countryName: 'Suriname',
    timeZone: 'America/Paramaribo',
    GMTOffset: 'UTC -03:40',
  },
  {
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    timeZone: 'Arctic/Longyearbyen',
    GMTOffset: 'UTC +00:43',
  },
  {
    countryCode: 'SZ',
    countryName: 'Swaziland',
    timeZone: 'Africa/Mbabane',
    GMTOffset: 'UTC +01:52',
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    timeZone: 'Europe/Stockholm',
    GMTOffset: 'UTC +01:12',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    timeZone: 'Europe/Zurich',
    GMTOffset: 'UTC +00:34',
  },
  {
    countryCode: 'SY',
    countryName: 'Syrian Arab Republic',
    timeZone: 'Asia/Damascus',
    GMTOffset: 'UTC +02:25',
  },
  {
    countryCode: 'TW',
    countryName: 'Taiwan, Province of China',
    timeZone: 'Asia/Taipei',
    GMTOffset: 'UTC +08:06',
  },
  {
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    timeZone: 'Asia/Dushanbe',
    GMTOffset: 'UTC +04:35',
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania, United Republic of',
    timeZone: 'Africa/Dar_es_Salaam',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    timeZone: 'Asia/Bangkok',
    GMTOffset: 'UTC +06:42',
  },
  {
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    timeZone: 'Asia/Dili',
    GMTOffset: 'UTC +08:22',
  },
  {
    countryCode: 'TG',
    countryName: 'Togo',
    timeZone: 'Africa/Lome',
    GMTOffset: 'UTC -00:16',
  },
  {
    countryCode: 'TK',
    countryName: 'Tokelau',
    timeZone: 'Pacific/Fakaofo',
    GMTOffset: 'UTC -11:24',
  },
  {
    countryCode: 'TO',
    countryName: 'Tonga',
    timeZone: 'Pacific/Tongatapu',
    GMTOffset: 'UTC +12:19',
  },
  {
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    timeZone: 'America/Port_of_Spain',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    timeZone: 'Africa/Tunis',
    GMTOffset: 'UTC +00:40',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    timeZone: 'Europe/Istanbul',
    GMTOffset: 'UTC +01:55',
  },
  {
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    timeZone: 'Asia/Ashgabat',
    GMTOffset: 'UTC +03:53',
  },
  {
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    timeZone: 'America/Grand_Turk',
    GMTOffset: 'UTC -04:44',
  },
  {
    countryCode: 'TV',
    countryName: 'Tuvalu',
    timeZone: 'Pacific/Funafuti',
    GMTOffset: 'UTC +11:56',
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    timeZone: 'Africa/Kampala',
    GMTOffset: 'UTC +02:27',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Kiev',
    GMTOffset: 'UTC +02:02',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Simferopol',
    GMTOffset: 'UTC +02:16',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Uzhgorod',
    GMTOffset: 'UTC +01:29',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    timeZone: 'Europe/Zaporozhye',
    GMTOffset: 'UTC +02:20',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    timeZone: 'Asia/Dubai',
    GMTOffset: 'UTC +03:41',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    timeZone: 'Europe/London',
    GMTOffset: 'UTC -00:01',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Adak',
    GMTOffset: 'UTC +12:13',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Anchorage',
    GMTOffset: 'UTC +14:00',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Boise',
    GMTOffset: 'UTC -07:44',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Chicago',
    GMTOffset: 'UTC -05:50',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Denver',
    GMTOffset: 'UTC -06:59',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Detroit',
    GMTOffset: 'UTC -05:32',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Indianapolis',
    GMTOffset: 'UTC -05:44',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Knox',
    GMTOffset: 'UTC -05:46',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Marengo',
    GMTOffset: 'UTC -05:45',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Petersburg',
    GMTOffset: 'UTC -05:49',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Tell_City',
    GMTOffset: 'UTC -05:47',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Vevay',
    GMTOffset: 'UTC -05:40',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Vincennes',
    GMTOffset: 'UTC -05:50',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Indiana/Winamac',
    GMTOffset: 'UTC -05:46',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Juneau',
    GMTOffset: 'UTC +15:02',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Kentucky/Louisville',
    GMTOffset: 'UTC -05:43',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Kentucky/Monticello',
    GMTOffset: 'UTC -05:39',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Los_Angeles',
    GMTOffset: 'UTC -07:52',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Menominee',
    GMTOffset: 'UTC -05:50',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Metlakatla',
    GMTOffset: 'UTC +15:13',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/New_York',
    GMTOffset: 'UTC -04:56',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Nome',
    GMTOffset: 'UTC +12:58',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/Beulah',
    GMTOffset: 'UTC -06:47',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/Center',
    GMTOffset: 'UTC -06:45',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/North_Dakota/New_Salem',
    GMTOffset: 'UTC -06:45',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Phoenix',
    GMTOffset: 'UTC -07:28',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Sitka',
    GMTOffset: 'UTC +14:58',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'America/Yakutat',
    GMTOffset: 'UTC +14:41',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    timeZone: 'Pacific/Honolulu',
    GMTOffset: 'UTC -10:31',
  },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    timeZone: 'Pacific/Midway',
    GMTOffset: 'UTC +12:37',
  },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    timeZone: 'Pacific/Wake',
    GMTOffset: 'UTC +11:06',
  },
  {
    countryCode: 'UY',
    countryName: 'Uruguay',
    timeZone: 'America/Montevideo',
    GMTOffset: 'UTC -03:44',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    timeZone: 'Asia/Samarkand',
    GMTOffset: 'UTC +04:27',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    timeZone: 'Asia/Tashkent',
    GMTOffset: 'UTC +04:37',
  },
  {
    countryCode: 'VU',
    countryName: 'Vanuatu',
    timeZone: 'Pacific/Efate',
    GMTOffset: 'UTC +11:13',
  },
  {
    countryCode: 'VE',
    countryName: 'Venezuela, Bolivarian Republic of',
    timeZone: 'America/Caracas',
    GMTOffset: 'UTC -04:27',
  },
  {
    countryCode: 'VN',
    countryName: 'Viet Nam',
    timeZone: 'Asia/Ho_Chi_Minh',
    GMTOffset: 'UTC +07:06',
  },
  {
    countryCode: 'VG',
    countryName: 'Virgin Islands, British',
    timeZone: 'America/Tortola',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'VI',
    countryName: 'Virgin Islands, U.S.',
    timeZone: 'America/St_Thomas',
    GMTOffset: 'UTC -04:24',
  },
  {
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    timeZone: 'Pacific/Wallis',
    GMTOffset: 'UTC +12:15',
  },
  {
    countryCode: 'EH',
    countryName: 'Western Sahara',
    timeZone: 'Africa/El_Aaiun',
    GMTOffset: 'UTC -00:52',
  },
  {
    countryCode: 'YE',
    countryName: 'Yemen',
    timeZone: 'Asia/Aden',
    GMTOffset: 'UTC +03:06',
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    timeZone: 'Africa/Lusaka',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    timeZone: 'Africa/Harare',
    GMTOffset: 'UTC +02:10',
  },
  {
    countryCode: 'AX',
    countryName: 'Åland Islands',
    timeZone: 'Europe/Mariehamn',
    GMTOffset: 'UTC +01:39',
  },
]
