// <MODULE>__<MODULE_NAME>___<SPECIFIED_STORE_KEY>

/**
 *
 *
 *
 * GLOBALS
 */
export const LANGUAGE = 'LANGUAGE'
export const FONT = 'FONT'

/**
 *
 *
 *
 * LAYOUTS
 */
export const LAYOUT__NAVBAR___SEARCH_QUERY = 'LAYOUT__NAVBAR___SEARCH_QUERY'
export const LAYOUT__NAVBAR___SEARCH_BOX_FOCUSED = 'LAYOUT__NAVBAR___SEARCH_BOX_FOCUSED'
export const LAYOUT__NAVBAR___ACTIVE_ITEM = 'LAYOUT__NAVBAR___ACTIVE_ITEM'

/**
 *
 *
 *
 * COMPONENTS
 */
export const PAGE__CREATE_NAP___POSTS_PICKUP_SEARCH_QUERY = 'PAGE__CREATE_NAP___POSTS_PICKUP_SEARCH_QUERY'
export const PAGE__CREATE_NAP___MENTIONS_PICKUP_SEARCH_QUERY = 'PAGE__CREATE_NAP___MENTIONS_PICKUP_SEARCH_QUERY'
export const PAGE__CREATE_NAP___TIME_PICKER_POPUP = 'PAGE__CREATE_NAP___TIME_PICKER_POPUP'
export const PAGE__CREATE_NAP___TIME_PICKER_VALUES = 'PAGE__CREATE_NAP___TIME_PICKER_VALUES'
export const PAGE__CREATE_NAP___TIME_PICKER_YEARS = 'PAGE__CREATE_NAP___TIME_PICKER_YEARS'
export const PAGE__CREATE_NAP___TIME_PICKER_MONTHS = 'PAGE__CREATE_NAP___TIME_PICKER_MONTHS'
export const PAGE__CREATE_NAP___TIME_PICKER_DAYS = 'PAGE__CREATE_NAP___TIME_PICKER_DAYS'
export const PAGE__CREATE_NAP___TIME_PICKER_HOURS = 'PAGE__CREATE_NAP___TIME_PICKER_HOURS'
export const PAGE__CREATE_NAP___TIME_PICKER_MINUTES = 'PAGE__CREATE_NAP___TIME_PICKER_MINUTES'

/**
 *
 *
 *
 * IN CREATE NAP PAGE
 */
export const PAGE__CREATE_NAP___ACTIVE_OPTION = 'PAGE__CREATE_NAP___ACTIVE_OPTION'
export const PAGE__CREATE_NAP___ACTIVE_ITEM_ID = 'PAGE__CREATE_NAP___ACTIVE_ITEM_ID'
export const PAGE__CREATE_NAP___POSTS_PICK_UP_VISIBILITY = 'PAGE__CREATE_NAP___POSTS_PICK_UP_VISIBILITY'
export const PAGE__CREATE_NAP___MENTION_PICK_UP_VISIBILITY = 'PAGE__CREATE_NAP___MENTION_PICK_UP_VISIBILITY'
export const PAGE__CREATE_NAP___GIF_POPUP_VISIBILITY = 'PAGE__CREATE_NAP___GIF_POPUP_VISIBILITY'
export const PAGE__CREATE_NAP___MENTION_POPUP_VISIBILITY = 'PAGE__CREATE_NAP___MENTION_POPUP_VISIBILITY'
export const PAGE__CREATE_NAP___SHOW_MORE_OPTIONS = 'PAGE__CREATE_NAP___SHOW_MORE_OPTIONS'
