export const LANGUAGE = 'LANGUAGE'

export const LAYOUT_NAVBAR_SEARCH_QUERY = 'LAYOUT_NAVBAR_SEARCH_QUERY'

export const LAYOUT_NAVBAR_SEARCH_BOX_FOCUSED = 'LAYOUT_NAVBAR_SEARCH_BOX_FOCUSED'

export const FONT = 'FONT'

export const BOTTOM_NAVBAR_ACTIVE_ITEM = 'BOTTOM_NAVBAR_ACTIVE_ITEM'
