// <MODULE>__<MODULE_NAME>___<UNIQUE_STORE_KEY>
// keys end with underscore has a dynamic string | number

/**
 *
 *
 *
 * PROVIDERS
 */
export const PROVIDER__INTERNATIONALIZATION___LANGUAGE = 'PROVIDER__INTERNATIONALIZATION___LANGUAGE'

/**
 *
 *
 *
 * HOOKS
 */
export const HOOK__USER_FONT___FONT = 'HOOK__USER_FONT___FONT'
export const HOOK__USE_AUTO_BREAKPOINT___CURRENT_WINDOW_BREAKPOINT = 'HOOK__USE_AUTO_BREAKPOINT___CURRENT_WINDOW_BREAKPOINT'

/**
 *
 *
 *
 * LAYOUTS
 */
export const LAYOUT__NAVBAR___SEARCH_QUERY = 'LAYOUT__NAVBAR___SEARCH_QUERY'
export const LAYOUT__NAVBAR___SEARCH_BOX_FOCUSED = 'LAYOUT__NAVBAR___SEARCH_BOX_FOCUSED'
export const LAYOUT__BOTTOM_NAVBAR___ACTIVE_ITEM = 'LAYOUT__BOTTOM_NAVBAR___ACTIVE_ITEM'

/**
 *
 *
 *
 * COMPONENTS
 */
export const PAGE__CREATE_NAP___POSTS_PICKUP_SEARCH_QUERY = 'PAGE__CREATE_NAP___POSTS_PICKUP_SEARCH_QUERY'
export const PAGE__CREATE_NAP___MENTIONS_PICKUP_SEARCH_QUERY = 'PAGE__CREATE_NAP___MENTIONS_PICKUP_SEARCH_QUERY'
export const PAGE__CREATE_NAP___GIFS_PICKUP_SEARCH_QUERY = 'PAGE__CREATE_NAP___GIFS_PICKUP_SEARCH_QUERY'
export const PAGE__CREATE_NAP___TIME_PICKER_POPUP = 'PAGE__CREATE_NAP___TIME_PICKER_POPUP'
export const PAGE__CREATE_NAP___TIME_PICKER_MINUTE = 'PAGE__CREATE_NAP___TIME_PICKER_MINUTE'
export const PAGE__CREATE_NAP___TIME_PICKER_HOUR = 'PAGE__CREATE_NAP___TIME_PICKER_HOUR'
export const PAGE__CREATE_NAP___TIME_PICKER_DAY = 'PAGE__CREATE_NAP___TIME_PICKER_DAY'
export const PAGE__CREATE_NAP___TIME_PICKER_MONTH = 'PAGE__CREATE_NAP___TIME_PICKER_MONTH'
export const PAGE__CREATE_NAP___TIME_PICKER_YEAR = 'PAGE__CREATE_NAP___TIME_PICKER_YEAR'
export const PAGE__CREATE_NAO___DATE_TIME_PICKER_MINIMUM_DATE = 'PAGE__CREATE_NAO___DATE_TIME_PICKER_MINIMUM_DATE'
export const COMPONENT__NAP_VIEWER___NAP_VIEWER_POPUP_VISIBILITY = 'COMPONENT__NAP_VIEWER___NAP_VIEWER_POPUP_VISIBILITY'
export const COMPONENT__NAP_VIEWER___NAP_GROUP_INDEX = 'COMPONENT__NAP_VIEWER___NAP_GROUP_INDEX'
export const COMPONENT__NAP_VIEWER___NAP_INDEX_ = 'COMPONENT__NAP_VIEWER___NAP_INDEX_'
export const COMPONENT__NAP_VIEWER___COMPILED_ELEMENTS_ = 'COMPONENT__NAP_VIEWER___COMPILED_ELEMENTS_'

/**
 *
 *
 *
 * IN CREATE NAP PAGE
 */
export const PAGE__CREATE_NAP___ACTIVE_OPTION = 'PAGE__CREATE_NAP___ACTIVE_OPTION'
export const PAGE__CREATE_NAP___ACTIVE_ITEM_ID = 'PAGE__CREATE_NAP___ACTIVE_ITEM_ID'
export const PAGE__CREATE_NAP___POSTS_PICK_UP_VISIBILITY = 'PAGE__CREATE_NAP___POSTS_PICK_UP_VISIBILITY'
export const PAGE__CREATE_NAP___MENTION_PICK_UP_VISIBILITY = 'PAGE__CREATE_NAP___MENTION_PICK_UP_VISIBILITY'
export const PAGE__CREATE_NAP___GIPHY_PICK_UP_VISIBILITY = 'PAGE__CREATE_NAP___GIPHY_PICK_UP_VISIBILITY'
export const PAGE__CREATE_NAP___MENTION_POPUP_VISIBILITY = 'PAGE__CREATE_NAP___MENTION_POPUP_VISIBILITY'
export const PAGE__CREATE_NAP___SHOW_MORE_OPTIONS = 'PAGE__CREATE_NAP___SHOW_MORE_OPTIONS'
export const PAGE__CREATE_NAP___DATE_TIME_PICKER_ACTIVE_LAYER = 'PAGE__CREATE_NAP___DATE_TIME_PICKER_ACTIVE_LAYER'
export const PAGE__CREATE_NAP___EDIT_LINK_POPUP_VISIBILITY = 'PAGE__CREATE_NAP___EDIT_LINK_POPUP_VISIBILITY'
export const PAGE__CREATE_NAP___EDIT_LINK_POPUP_TEXT_AND_REF = 'PAGE__CREATE_NAP___EDIT_LINK_POPUP_TEXT_AND_REF'
