export const LANGUAGE = 'LANGUAGE'

export const LAYOUT_NAVBAR_SEARCH_QUERY = 'LAYOUT_NAVBAR_SEARCH_QUERY'

export const LAYOUT_NAVBAR_SEARCH_BOX_FOCUSED = 'LAYOUT_NAVBAR_SEARCH_BOX_FOCUSED'

export const FONT = 'FONT'

export const BOTTOM_NAVBAR_ACTIVE_ITEM = 'BOTTOM_NAVBAR_ACTIVE_ITEM'

export const SHOW_MORE_OPTIONS_IN_CREATE_NAP_PAGE = 'SHOW_MORE_OPTIONS_IN_CREATE_NAP_PAGE'

export const IN_CREATE_NAP_PAGE_ACTIVE_OPTION = 'IN_CREATE_NAP_PAGE_ACTIVE_OPTION'

export const IN_CREATE_NAP_PAGE_ACTIVE_ITEM_ID = 'IN_CREATE_NAP_PAGE_ACTIVE_ITEM_ID'
